"""Local user / profile / leaderboard store.

The whole app runs on a single FastAPI process per user, so this is a
simple JSON-backed registry. When users point their clients at the
same backend host, they share a leaderboard.

Each user keeps:
  • client_id  — UUID generated by the frontend on first launch
  • nickname   — display name chosen at onboarding
  • avatar     — emoji string ("🦊", "♟", …)
  • stats      — counters maintained server-side as attempts arrive
  • rating     — current Glicko-lite rating (last applied delta)
  • elo_history — chronological list of {ts, rating, delta, outcome}
  • parties    — per-user history of party-match summaries
  • last_seen  — unix-seconds timestamp of last heartbeat / attempt
"""
from __future__ import annotations

import json
import threading
import time
from typing import Any

from .settings import settings

_USERS_PATH = settings.data_dir / "users.json"
_LOCK = threading.Lock()


def _ensure_dir() -> None:
    _USERS_PATH.parent.mkdir(parents=True, exist_ok=True)


def _load() -> dict[str, Any]:
    if not _USERS_PATH.exists():
        return {"users": {}}
    try:
        with _USERS_PATH.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {"users": {}}
    if not isinstance(data, dict):
        return {"users": {}}
    if "users" not in data or not isinstance(data["users"], dict):
        data["users"] = {}
    return data


def _save(data: dict[str, Any]) -> None:
    _ensure_dir()
    tmp = _USERS_PATH.with_suffix(".json.tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    tmp.replace(_USERS_PATH)


def _blank_user(client_id: str, nickname: str, avatar: str) -> dict[str, Any]:
    now = int(time.time())
    return {
        "client_id": client_id,
        "nickname": nickname,
        "avatar": avatar,
        "rating": 1200,
        "stats": {
            "solved": 0,
            "wrong": 0,
            "skipped": 0,
            "games": 0,
            "best_streak": 0,
            "current_streak": 0,
        },
        "elo_history": [
            {"ts": now, "rating": 1200, "delta": 0, "outcome": "init"},
        ],
        "parties": [],
        "created_at": now,
        "last_seen": now,
    }


def upsert_user(
    client_id: str,
    nickname: str,
    avatar: str,
) -> dict[str, Any]:
    """Create the user row on first use, otherwise patch nickname/avatar."""
    nickname = (nickname or "").strip()[:32] or "Гость"
    avatar = (avatar or "").strip()[:8] or "♟"
    with _LOCK:
        data = _load()
        users = data["users"]
        u = users.get(client_id)
        if u is None:
            u = _blank_user(client_id, nickname, avatar)
            users[client_id] = u
        else:
            u["nickname"] = nickname
            u["avatar"] = avatar
        u["last_seen"] = int(time.time())
        _save(data)
        return dict(u)


def heartbeat(client_id: str) -> None:
    with _LOCK:
        data = _load()
        u = data["users"].get(client_id)
        if not u:
            return
        u["last_seen"] = int(time.time())
        _save(data)


def get_user(client_id: str) -> dict[str, Any] | None:
    data = _load()
    u = data["users"].get(client_id)
    return dict(u) if u else None


def _summarize(u: dict[str, Any]) -> dict[str, Any]:
    """Public projection used by the leaderboard list."""
    s = u.get("stats") or {}
    games = int(s.get("games") or 0)
    solved = int(s.get("solved") or 0)
    wrong = int(s.get("wrong") or 0)
    skipped = int(s.get("skipped") or 0)
    win_pct = (solved / games * 100.0) if games else 0.0
    return {
        "client_id": u.get("client_id"),
        "nickname": u.get("nickname"),
        "avatar": u.get("avatar"),
        "rating": int(u.get("rating") or 1200),
        "games": games,
        "solved": solved,
        "wrong": wrong,
        "skipped": skipped,
        "win_pct": round(win_pct, 1),
        "best_streak": int(s.get("best_streak") or 0),
        "current_streak": int(s.get("current_streak") or 0),
        "last_seen": int(u.get("last_seen") or 0),
    }


def list_users() -> list[dict[str, Any]]:
    data = _load()
    rows = [_summarize(u) for u in data["users"].values()]
    rows.sort(key=lambda r: (-r["rating"], -r["games"], r["nickname"] or ""))
    return rows


def record_puzzle_attempt(
    client_id: str,
    *,
    outcome: str,
    delta: int,
    new_rating: int,
    puzzle_id: str | None,
    puzzle_rating: int | None,
    solve_ms: int | None,
) -> dict[str, Any] | None:
    """Persist a single puzzle outcome. Returns updated user row."""
    if outcome not in ("solved", "solved-hint", "failed", "skipped"):
        return None
    new_rating = max(400, min(3000, int(new_rating)))
    delta = int(delta)
    now = int(time.time())
    with _LOCK:
        data = _load()
        u = data["users"].get(client_id)
        if u is None:
            # Auto-register a placeholder so the attempt isn't lost.
            u = _blank_user(client_id, "Гость", "♟")
            data["users"][client_id] = u
        s = u.setdefault(
            "stats",
            {
                "solved": 0,
                "wrong": 0,
                "skipped": 0,
                "games": 0,
                "best_streak": 0,
                "current_streak": 0,
            },
        )
        s["games"] = int(s.get("games") or 0) + 1
        if outcome in ("solved", "solved-hint"):
            s["solved"] = int(s.get("solved") or 0) + 1
            if outcome == "solved":
                s["current_streak"] = int(s.get("current_streak") or 0) + 1
                if s["current_streak"] > int(s.get("best_streak") or 0):
                    s["best_streak"] = s["current_streak"]
        elif outcome == "failed":
            s["wrong"] = int(s.get("wrong") or 0) + 1
            s["current_streak"] = 0
        else:  # skipped
            s["skipped"] = int(s.get("skipped") or 0) + 1
            s["current_streak"] = 0
        u["rating"] = new_rating
        u["last_seen"] = now
        history = u.setdefault("elo_history", [])
        history.append(
            {
                "ts": now,
                "rating": new_rating,
                "delta": delta,
                "outcome": outcome,
                "puzzle_id": puzzle_id,
                "puzzle_rating": puzzle_rating,
                "solve_ms": solve_ms,
            }
        )
        # Keep history bounded; 5000 entries is plenty per local user.
        if len(history) > 5000:
            del history[: len(history) - 5000]
        _save(data)
        return dict(u)


def record_party_result(client_id: str, summary: dict[str, Any]) -> None:
    """Append a party-match summary to the user's history."""
    if not isinstance(summary, dict):
        return
    with _LOCK:
        data = _load()
        u = data["users"].get(client_id)
        if u is None:
            return
        parties = u.setdefault("parties", [])
        parties.append({"ts": int(time.time()), **summary})
        if len(parties) > 200:
            del parties[: len(parties) - 200]
        _save(data)


def reset_for_tests() -> None:
    """Test-only helper: drop the on-disk store."""
    with _LOCK:
        if _USERS_PATH.exists():
            _USERS_PATH.unlink()
